server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/goodscm
        username: longlh
        password: solong1980
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        connectionProperties: druid.stat.mergeSql=true

mybatis:
  mapper-locations: classpath:com/xlw/goodscm/dao/*.xml
  type-aliases-package: com.xlw.goodscm.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
logging:
  level: 
    com: trace

spring:
  redis:
    shiro:
      host :127.0.0.1
spring:
  redis:
    shiro:
      port :6371
spring:
  redis:
    shiro:
      timeout :1000
spring:
  redis:
    shiro:
      password : 